using UnityEngine;
using UnityEngine.Animations.Rigging;

namespace Atomic.Character.Module
{
    public class AiWeaponVisuals : MonoBehaviour
    {
        private Animator anim;
        private bool isGrabbingWeapon;

        #region Gun transforms region
        [SerializeField] private Transform[] gunTransforms;

        [SerializeField] private Transform pistol;
        [SerializeField] private Transform revolver;
        [SerializeField] private Transform autoRifle;
        [SerializeField] private Transform shotgun;
        [SerializeField] private Transform rifle;

        private Transform currentGun;
        #endregion

        [Header("Rig ")]
        [SerializeField] private float rigWeightIncreaseRate;
        private bool shouldIncrease_RigWeight;
        private Rig rig;

        [Header("Left hand IK")]
        [SerializeField] private float leftHandIkWeightIncreaseRate;
        [SerializeField] private TwoBoneIKConstraint leftHandIK;
        [SerializeField] private Transform leftHandIK_Target;
        private bool shouldIncrease_LeftHandIKWieght;

        private void Start()
        {
            anim = GetComponentInChildren<Animator>();
            rig = GetComponentInChildren<Rig>();

            SwitchOn(pistol);
        }

        private void Update()
        {
            CheckWeaponSwitch();


            if (Input.GetKeyDown(KeyCode.R) && isGrabbingWeapon == false)
            {
                anim.SetTrigger("Reload");
                ReduceRigWeight();
            }

            UpdateRigWigth();
            UpdateLeftHandIKWeight();
        }

        private void UpdateLeftHandIKWeight()
        {
            if (shouldIncrease_LeftHandIKWieght)
            {
                leftHandIK.weight += leftHandIkWeightIncreaseRate * Time.deltaTime;

                if (leftHandIK.weight >= 1)
                    shouldIncrease_LeftHandIKWieght = false;
            }
        }
        private void UpdateRigWigth()
        {
            if (shouldIncrease_RigWeight)
            {
                rig.weight += rigWeightIncreaseRate * Time.deltaTime;

                if (rig.weight >= 1)
                    shouldIncrease_RigWeight = false;
            }
        }
        private void ReduceRigWeight()
        {
            rig.weight = .15f;
        }


        private void PlayWeaponGrabAnimation(GrabType grabType)
        {
            leftHandIK.weight = 0;
            ReduceRigWeight();
            anim.SetFloat("WeaponGrabType", ((float)grabType));
            anim.SetTrigger("WeaponGrab");

            SetBusyGrabbingWeaponTo(true);
        }
        public void SetBusyGrabbingWeaponTo(bool busy)
        {
            isGrabbingWeapon = busy;
            anim.SetBool("BusyGrabbingWeapon", isGrabbingWeapon);
        }

        public void MaximizeRigWeight() => shouldIncrease_RigWeight = true;
        public void MaximizeLeftHandWeight() => shouldIncrease_LeftHandIKWieght = true;


        private void SwitchOn(Transform gunTransform)
        {
            SwitchOffGuns();
            gunTransform.gameObject.SetActive(true);
            currentGun = gunTransform;

            AttachLeftHand();
        }
        private void SwitchOffGuns()
        {
            for (int i = 0; i < gunTransforms.Length; i++)
            {
                gunTransforms[i].gameObject.SetActive(false);
            }
        }
        private void AttachLeftHand()
        {
            Transform targetTransform = currentGun.GetComponentInChildren<LeftHandTargetTransform>().transform;

            leftHandIK_Target.localPosition = targetTransform.localPosition;
            leftHandIK_Target.localRotation = targetTransform.localRotation;
        }
        private void SwitchAnimationLayer(int layerIndex)
        {
            for (int i = 1; i < anim.layerCount; i++)
            {
                anim.SetLayerWeight(i, 0);
            }

            anim.SetLayerWeight(layerIndex, 1);
        }



        private void CheckWeaponSwitch()
        {
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                SwitchOn(pistol);
                SwitchAnimationLayer(1);
                PlayWeaponGrabAnimation(GrabType.SideGrab);
            }

            if (Input.GetKeyDown(KeyCode.Alpha2))
            {

                SwitchOn(revolver);
                SwitchAnimationLayer(1);
                PlayWeaponGrabAnimation(GrabType.SideGrab);
            }

            if (Input.GetKeyDown(KeyCode.Alpha3))
            {
                SwitchOn(autoRifle);
                SwitchAnimationLayer(1);
                PlayWeaponGrabAnimation(GrabType.BackGrab);
            }

            if (Input.GetKeyDown(KeyCode.Alpha4))
            {
                SwitchOn(shotgun);
                SwitchAnimationLayer(2);
                PlayWeaponGrabAnimation(GrabType.BackGrab);
            }

            if (Input.GetKeyDown(KeyCode.Alpha5))
            {
                SwitchOn(rifle);
                SwitchAnimationLayer(3);
                PlayWeaponGrabAnimation(GrabType.BackGrab);
            }
        }
    }

    public enum GrabType { SideGrab, BackGrab };
}
